server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Tenta carregar o arquivo, se não achar, redireciona para o index.html do Angular
        try_files $uri $uri/ /index.html;
    }
}